		dc.l Solid_AIZ1
		dc.l Solid_AIZ2
		dc.l Solid_HCZ1
		dc.l Solid_HCZ2
		dc.l Solid_MGZ1
		dc.l Solid_MGZ2
		dc.l Solid_CNZ
		dc.l Solid_CNZ
		dc.l Solid_FBZ
		dc.l Solid_FBZ
		dc.l Solid_ICZ1
		dc.l Solid_ICZ2
		dc.l Solid_LBZ1
		dc.l Solid_LBZ2
		dc.l Solid_MHZ
		dc.l Solid_MHZ
		dc.l Solid_SOZ
		dc.l Solid_SOZ
		dc.l Solid_LRZ1
		dc.l Solid_LRZ2
		dc.l Solid_SSZ1
		dc.l Solid_SSZ2
		dc.l Solid_DEZ
		dc.l Solid_DEZ
		dc.l Solid_DDZ
		dc.l Solid_DDZ
		dc.l Solid_Pachinko_Special
		dc.l Solid_Pachinko_Special
		dc.l Solid_ALZ
		dc.l Solid_ALZ
		dc.l Solid_BPZ
		dc.l Solid_BPZ
		dc.l Solid_DPZ
		dc.l Solid_DPZ
		dc.l Solid_CGZ
		dc.l Solid_CGZ
		dc.l Solid_EMZ
		dc.l Solid_EMZ
		dc.l Solid_Gumball_Special
		dc.l Solid_Gumball_Special
		dc.l Solid_Pachinko_Special
		dc.l Solid_Pachinko_Special
		dc.l Solid_Slots_Special
		dc.l Solid_Slots_Special
		dc.l Solid_LRZBoss
		dc.l Solid_HPZ
		dc.l Solid_HPZ
		dc.l Solid_HPZ